### PR TITLE
fix: update twitter link

### PR DESCRIPTION
**Pull request by magnasilvar**
The current Twitter link to **Alan engineering** is wrong.
| Wrong link | Good link |
|-|-|
| https://twitter.com/alan_engineering | https://twitter.com/alanengineering |

### CODE REVIEW

**Review by tdudouet — APPROVED** [review]

**Comment by magnasilvar** [comment]
Thanks @tdudouet for your approval! 🙏
I don't know the @alan-eu process to merge a pull request. If it belongs to me, sorry but I don't have write access to this repository (mandatory to merge pull request).

**Comment by tdudouet** [comment]
@magnasilvar Merged, thanks a lot for your fix 🙏

**Comment by arnaudriegert** [comment]
> I don't know the @alan-eu process to merge a pull request. If it belongs to me, sorry but I don't have write access to this repository (mandatory to merge pull request).

We would need to [hire you](https://jobs.lever.co/alan/2584ab42-2bed-44ea-b643-13e6f6927ccc) first 🙂

**Comment by magnasilvar** [comment]
@arnaudpeich it seems really hard to get through your process! But why not: challenge accepted! 😁

**Comment by arnaudriegert** [comment]
@magnasilvar if you haven't seen already, here's a great [article](https://medium.com/alan/engineering-hiring-process-at-alan-f37a53f8f916) by @ElPicador explaining our process!

And here's the [job posting](https://jobs.lever.co/alan/2584ab42-2bed-44ea-b643-13e6f6927ccc).

We're looking forward to meeting you 🙂

**Comment by arnaudriegert** [comment]
Welcome to @alan-eu, @magnasilvar 🎉

**Pull request merged**
