### PR TITLE
chore: update readme illustration

### PR DESCRIPTION
**Pull request by GitSquared**
- update the icon to the new visual identity while keeping an eng-specific vibe
- add link to job posts

💡 I also re-enabled the GitHub Actions workflow that automatically updates the blog post links, it had gone stale

### CODE REVIEW

**Comment by gary-cohen** [comment]
the replacement image is quite small. is this intended?

**Review by ElPicador — APPROVED** [review]
I wouldn't change the image, or we change it everywhere (twitter, medium, etc)

**Comment by gary-cohen** [comment]
i agree with not changing it, or have design create a new one for us with ali.

**Comment by GitSquared** [comment]
@gary-cohen previous one was 1000+px wide but truncated to 200px in the README code, so I put a 200px wide instead to save some space

@ElPicador agreed - I didn't see we still used the old one on twitter and Medium 🙁

**Comment by GitSquared** [comment]
removed the image change for now, will go through a design request

**Pull request merged**
